#!/bin/bash
# Install puffer panel

echo "
  ______          _            __   __
 |___  /         | |           \ \ / /
    / / __ _ _ __| | _____  ___ \ V / 
   / / / _\` | '__| |/ / _ \/ __| > <  
  / /_| (_| | |  |   < (_) \__ \/ . \ 
 /_____\__,_|_|  |_|\_\___/|___/_/ \_\


                  ZarkosX
"

apt update
apt install sudo
apt install systemctl
curl -s https://packagecloud.io/install/repositories/pufferpanel/pufferpanel/script.deb.sh?any=true | sudo bash
sudo apt update
sudo apt-get install pufferpanel
