#!/bin/bash
# Install puffer panel
apt update
apt install sudo
apt install systemctl
curl -s https://raw.githubusercontent.com/Omar9282jwee/Puffer-Panel/refs/heads/main/script.deb.sh?any=true | sudo bash
sudo apt update
sudo apt-get install pufferpanel
